// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace RiftRpg.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260908222227_CriadaFichaDePersonagem")]
    partial class CriadaFichaDePersonagem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RiftRpg.Models.Ficha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Acrobacias")
                        .HasColumnType("integer");

                    b.Property<string>("Anotacoes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ArmasBrancas")
                        .HasColumnType("integer");

                    b.Property<int>("Atletismo")
                        .HasColumnType("integer");

                    b.Property<int>("Conhecimento")
                        .HasColumnType("integer");

                    b.Property<int>("Constituicao")
                        .HasColumnType("integer");

                    b.Property<int>("Crime")
                        .HasColumnType("integer");

                    b.Property<string>("Despertar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Destreza")
                        .HasColumnType("integer");

                    b.Property<int>("Direcao")
                        .HasColumnType("integer");

                    b.Property<int>("Domar")
                        .HasColumnType("integer");

                    b.Property<string>("Equipamentos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estilo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Forca")
                        .HasColumnType("integer");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Furtividade")
                        .HasColumnType("integer");

                    b.Property<string>("Habilidades")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Historia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("Iniciativa")
                        .HasColumnType("integer");

                    b.Property<int>("Intelecto")
                        .HasColumnType("integer");

                    b.Property<int>("Intimidacao")
                        .HasColumnType("integer");

                    b.Property<int>("Intuicao")
                        .HasColumnType("integer");

                    b.Property<int>("Investigacao")
                        .HasColumnType("integer");

                    b.Property<int>("Labia")
                        .HasColumnType("integer");

                    b.Property<int>("Lutar")
                        .HasColumnType("integer");

                    b.Property<int>("Medicina")
                        .HasColumnType("integer");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<string>("NomePersonagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ocultismo")
                        .HasColumnType("integer");

                    b.Property<int>("Percepcao")
                        .HasColumnType("integer");

                    b.Property<int>("Poder")
                        .HasColumnType("integer");

                    b.Property<int>("Pontaria")
                        .HasColumnType("integer");

                    b.Property<int>("PontosManaAtual")
                        .HasColumnType("integer");

                    b.Property<int>("PontosManaMax")
                        .HasColumnType("integer");

                    b.Property<int>("PontosVidaAtual")
                        .HasColumnType("integer");

                    b.Property<int>("PontosVidaMax")
                        .HasColumnType("integer");

                    b.Property<int>("Psicologia")
                        .HasColumnType("integer");

                    b.Property<int>("Reflexos")
                        .HasColumnType("integer");

                    b.Property<int>("Robustez")
                        .HasColumnType("integer");

                    b.Property<int>("Sobrevivencia")
                        .HasColumnType("integer");

                    b.Property<int>("Vontade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Fichas");
                });

            modelBuilder.Entity("RiftRpg.Models.InventarioFicha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Equipado")
                        .HasColumnType("boolean");

                    b.Property<int?>("FichaId")
                        .HasColumnType("integer");

                    b.Property<int>("IdFicha")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Peso")
                        .HasColumnType("integer");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FichaId");

                    b.ToTable("InventarioFichas");
                });

            modelBuilder.Entity("RiftRpg.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("RiftRpg.Models.InventarioFicha", b =>
                {
                    b.HasOne("RiftRpg.Models.Ficha", "Ficha")
                        .WithMany("Inventario")
                        .HasForeignKey("FichaId");

                    b.Navigation("Ficha");
                });

            modelBuilder.Entity("RiftRpg.Models.Ficha", b =>
                {
                    b.Navigation("Inventario");
                });
#pragma warning restore 612, 618
        }
    }
}
